name: test_reactive_form6
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:

  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  flutter_hooks: ^0.18.6
  flutter_riverpod: ^2.3.2
  freezed_annotation: ^2.1.0

  json_annotation: ^4.6.0

  reactive_forms: ^14.1.0

dev_dependencies:
  build_runner: ^2.2.0

  flutter_lints: ^1.0.0

  flutter_test:
    sdk: flutter

  freezed: ^2.0.4

  json_serializable: ^6.3.1

flutter:

  uses-material-design: true
